# Generated by Django 5.1.2 on 2024-11-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_rename_result_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='appartment_num',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_num',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip',
            field=models.TextField(),
        ),
    ]
